version: "3.7"

services:
  mssql-db:
    container_name: mssql_db
    image: "mcr.microsoft.com/mssql/server:2019"
    environment:
      - SA_PASSWORD=qwerty@123456
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "8033:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: ~
