version: "3.7"

services:
  pg1:
    container_name: pg1
    image: postgres:14.1-alpine
    env_file:
      - ./.env
    ports:
      - "15000:5432"
    volumes:
      - pg1_data:/var/lib/postgresql/data

  pg2:
    container_name: pg2
    image: postgres:14.1-alpine
    env_file:
      - ./.env
    ports:
      - "15001:5432"
    volumes:
      - pg2_data:/var/lib/postgresql/data

  pg3:
    container_name: pg2
    image: postgres:14.1-alpine
    env_file:
      - ./.env
    ports:
      - "15002:5432"
    volumes:
      - pg2_data:/var/lib/postgresql/data

volumes:
  pg1:
  pg2:
  pg3:

