version: "3.7"

services:
  postgres-db:
    container_name: postgres_db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@prunedge.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
