version: "3.7"

services:
  mssql-db:
      container_name: mssql_db
      image: "mcr.microsoft.com/mssql/server:2019"
      env_file:
        - ./.env
      ports:
        - "8033:1433"
      volumes:
        - mssql_volume:/var/opt/mssql

volumes:
  mssql_volume: ~
